name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:

jobs:
  default:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run setup-postgres
        uses: ./
        id: postgres

      - name: Run tests
        run: |
          python3 -m pip install --upgrade pip pytest psycopg
          python3 -m pytest -vv test_action.py
        env:
          CONNECTION_URI: ${{ steps.postgres.outputs.connection-uri }}
          EXPECTED_CONNECTION_URI: postgresql://postgres:postgres@localhost:5432/postgres
        shell: bash

  parametrized:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run setup-postgres
        uses: ./
        with:
          username: yoda
          password: GrandMaster
          database: jedi_order
          port: 34837
        id: postgres

      - name: Run tests
        run: |
          python3 -m pip install --upgrade pip pytest psycopg
          python3 -m pytest -vv test_action.py
        env:
          CONNECTION_URI: ${{ steps.postgres.outputs.connection-uri }}
          EXPECTED_CONNECTION_URI: postgresql://yoda:GrandMaster@localhost:34837/jedi_order
        shell: bash
